// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exam/test/features/profile/presentation/view/widgets/profile_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_online_exam/core/config/base_response/result.dart'
    as _i5;
import 'package:elevate_online_exam/core/helper/classes/params.dart' as _i9;
import 'package:elevate_online_exam/features/profile/domain/entities/user_entity.dart'
    as _i6;
import 'package:elevate_online_exam/features/profile/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:elevate_online_exam/features/profile/domain/use_cases/get_profile_data_use_case.dart'
    as _i3;
import 'package:elevate_online_exam/features/profile/domain/use_cases/update_profile_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileRepository_0 extends _i1.SmartFake
    implements _i2.ProfileRepository {
  _FakeProfileRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i3.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i4.Future<_i5.Result<_i6.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.UserEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.UserEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.UserEntity>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i8.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get profileRepository =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#profileRepository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i4.Future<_i5.Result<_i6.UserEntity>> call(_i9.EditProfileParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.UserEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.UserEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.UserEntity>>);
}
