// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exam/test/features/exams_tap/data/repositories/exams_tap_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_online_exam/core/config/base_response/result.dart'
    as _i5;
import 'package:elevate_online_exam/features/exams_tap/api/api_client/exams_tap_api_client.dart'
    as _i2;
import 'package:elevate_online_exam/features/exams_tap/api/datasources/exams_tap_remote_data_source_impl.dart'
    as _i3;
import 'package:elevate_online_exam/features/exams_tap/data/models/exams_response_dto.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExamsTapApiClient_0 extends _i1.SmartFake
    implements _i2.ExamsTapApiClient {
  _FakeExamsTapApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExamsTapRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamsTapRemoteDataSourceImpl extends _i1.Mock
    implements _i3.ExamsTapRemoteDataSourceImpl {
  MockExamsTapRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExamsTapApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeExamsTapApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.ExamsTapApiClient);

  @override
  _i4.Future<_i5.Result<_i6.ExamsResponseDto>> getExams({
    required Map<String, dynamic>? queries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExams, [], {#queries: queries}),
            returnValue: _i4.Future<_i5.Result<_i6.ExamsResponseDto>>.value(
              _i7.dummyValue<_i5.Result<_i6.ExamsResponseDto>>(
                this,
                Invocation.method(#getExams, [], {#queries: queries}),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.ExamsResponseDto>>);
}
