// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exam/test/features/explore/data/repositories/explore_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_online_exam/core/config/base_response/result.dart'
    as _i4;
import 'package:elevate_online_exam/core/helper/classes/params.dart' as _i6;
import 'package:elevate_online_exam/features/explore/data/datasources/explore_remote_data_source_contract.dart'
    as _i2;
import 'package:elevate_online_exam/features/explore/data/models/subjects_model/subject.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExploreRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockExploreRemoteDataSourceContract extends _i1.Mock
    implements _i2.ExploreRemoteDataSourceContract {
  MockExploreRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Subject>>> getSubjects(
    _i6.PaginationParams? paginationParams,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, [paginationParams]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Subject>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Subject>>>(
                this,
                Invocation.method(#getSubjects, [paginationParams]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Subject>>>);
}
