// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exam/test/features/exams_tap/presentation/view_model/cubit/exams_tap_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_online_exam/core/config/base_response/result.dart'
    as _i5;
import 'package:elevate_online_exam/features/exams_tap/domain/entities/paginated_exams.dart'
    as _i6;
import 'package:elevate_online_exam/features/exams_tap/domain/repositories/exams_tap_repository.dart'
    as _i2;
import 'package:elevate_online_exam/features/exams_tap/domain/use_cases/get_exams_on_subject_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExamsTapRepository_0 extends _i1.SmartFake
    implements _i2.ExamsTapRepository {
  _FakeExamsTapRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetExamsOnSubjectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExamsOnSubjectUseCase extends _i1.Mock
    implements _i3.GetExamsOnSubjectUseCase {
  MockGetExamsOnSubjectUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExamsTapRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeExamsTapRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ExamsTapRepository);

  @override
  set repository(_i2.ExamsTapRepository? value) => super.noSuchMethod(
    Invocation.setter(#repository, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.Result<_i6.PaginatedExams>> call({
    required String? subjectId,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#subjectId: subjectId, #page: page}),
            returnValue: _i4.Future<_i5.Result<_i6.PaginatedExams>>.value(
              _i7.dummyValue<_i5.Result<_i6.PaginatedExams>>(
                this,
                Invocation.method(#call, [], {
                  #subjectId: subjectId,
                  #page: page,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.PaginatedExams>>);
}
