// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exam/test/features/explore/presentation/view_model/cubit/explore_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_online_exam/core/config/base_response/result.dart'
    as _i5;
import 'package:elevate_online_exam/core/helper/classes/params.dart' as _i7;
import 'package:elevate_online_exam/features/explore/domain/entities/subject_entities.dart'
    as _i6;
import 'package:elevate_online_exam/features/explore/domain/repositories/explore_repository.dart'
    as _i2;
import 'package:elevate_online_exam/features/explore/domain/use_cases/get_all_subjects_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExploreRepository_0 extends _i1.SmartFake
    implements _i2.ExploreRepository {
  _FakeExploreRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllSubjectsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllSubjectsUseCase extends _i1.Mock
    implements _i3.GetAllSubjectsUseCase {
  MockGetAllSubjectsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExploreRepository get exploreRepository =>
      (super.noSuchMethod(
            Invocation.getter(#exploreRepository),
            returnValue: _FakeExploreRepository_0(
              this,
              Invocation.getter(#exploreRepository),
            ),
          )
          as _i2.ExploreRepository);

  @override
  _i4.Future<_i5.Result<List<_i6.SubjectEntities>>> call(
    _i7.PaginationParams? paginationParams,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [paginationParams]),
            returnValue:
                _i4.Future<_i5.Result<List<_i6.SubjectEntities>>>.value(
                  _i8.dummyValue<_i5.Result<List<_i6.SubjectEntities>>>(
                    this,
                    Invocation.method(#call, [paginationParams]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.SubjectEntities>>>);
}
